import {readFileSync} from "node:fs";
import {createClient} from "@supabase/supabase-js";
const env=Object.fromEntries(readFileSync(".env.local","utf8").split("\n").filter(l=>l.includes("=")&&!l.trim().startsWith("#")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i).trim(),l.slice(i+1).trim().replace(/^["']|["']$/g,"")]}));
const sb=createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const {data}=await sb.from("products").select("id,data").eq("id","standy").single();
const d=data.data;
const o=(d.options||[]).find(o=>o.label==="สีอะคริลิค");
console.log(JSON.stringify(o,null,1));
console.log("\n--- pricing cells keys sample (สีอะคริลิค เป็นแกนที่ 3) ---");
console.log(Object.keys(d.pricing.cells).filter(k=>k.startsWith("6cm")).slice(0,12).join("\n"));
console.log("\n--- ราคาบางช่อง ---");
for(const k of Object.keys(d.pricing.cells).filter(k=>k.startsWith("6cm│สกรีน 1 ด้าน"))) console.log(k, "=", d.pricing.cells[k].join("/"));
console.log("\ntiers:", d.pricing.tiers.map(t=>t.label).join(" · "));
